class VietnamBankBin {
  final String name;
  final String code;
  final String bin;

  const VietnamBankBin({
    required this.name,
    required this.code,
    required this.bin,
  });
}

const realVietnamBankBins = <VietnamBankBin>[
  VietnamBankBin(name: 'VietinBank', code: 'ICB', bin: '970415'),
  VietnamBankBin(name: 'Vietcombank', code: 'VCB', bin: '970436'),
  VietnamBankBin(name: 'BIDV', code: 'BIDV', bin: '970418'),
  VietnamBankBin(name: 'Agribank', code: 'VBA', bin: '970405'),
  VietnamBankBin(name: 'OCB', code: 'OCB', bin: '970448'),
  VietnamBankBin(name: 'MBBank', code: 'MB', bin: '970422'),
  VietnamBankBin(name: 'Techcombank', code: 'TCB', bin: '970407'),
  VietnamBankBin(name: 'ACB', code: 'ACB', bin: '970416'),
  VietnamBankBin(name: 'VPBank', code: 'VPB', bin: '970432'),
  VietnamBankBin(name: 'TPBank', code: 'TPB', bin: '970423'),
  VietnamBankBin(name: 'Sacombank', code: 'STB', bin: '970403'),
  VietnamBankBin(name: 'HDBank', code: 'HDB', bin: '970437'),
  VietnamBankBin(name: 'VietCapitalBank', code: 'VCCB', bin: '970454'),
  VietnamBankBin(name: 'SCB', code: 'SCB', bin: '970429'),
  VietnamBankBin(name: 'VIB', code: 'VIB', bin: '970441'),
  VietnamBankBin(name: 'SHB', code: 'SHB', bin: '970443'),
  VietnamBankBin(name: 'Eximbank', code: 'EIB', bin: '970431'),
  VietnamBankBin(name: 'MSB', code: 'MSB', bin: '970426'),
  VietnamBankBin(name: 'SaigonBank', code: 'SGICB', bin: '970400'),
  VietnamBankBin(name: 'BacABank', code: 'BAB', bin: '970409'),
  VietnamBankBin(name: 'PVcomBank', code: 'PVCB', bin: '970412'),
  VietnamBankBin(name: 'MBV', code: 'MBV', bin: '970414'),
  VietnamBankBin(name: 'NCB', code: 'NCB', bin: '970419'),
  VietnamBankBin(name: 'ShinhanBank', code: 'SHBVN', bin: '970424'),
  VietnamBankBin(name: 'ABBANK', code: 'ABB', bin: '970425'),
  VietnamBankBin(name: 'VietABank', code: 'VAB', bin: '970427'),
  VietnamBankBin(name: 'NamABank', code: 'NAB', bin: '970428'),
  VietnamBankBin(name: 'PGBank', code: 'PGB', bin: '970430'),
  VietnamBankBin(name: 'VietBank', code: 'VIETBANK', bin: '970433'),
  VietnamBankBin(name: 'BaoVietBank', code: 'BVB', bin: '970438'),
  VietnamBankBin(name: 'SeABank', code: 'SEAB', bin: '970440'),
  VietnamBankBin(name: 'COOPBANK', code: 'COOPBANK', bin: '970446'),
  VietnamBankBin(name: 'LPBank', code: 'LPB', bin: '970449'),
  VietnamBankBin(name: 'KienLongBank', code: 'KLB', bin: '970452'),
  VietnamBankBin(name: 'KBank', code: 'KBank', bin: '668888'),
  VietnamBankBin(name: 'HongLeong Bank', code: 'HLBVN', bin: '970442'),
  VietnamBankBin(
      name: 'KEB Hana Bank Hà Nội', code: 'KEBHANAHN', bin: '970467'),
  VietnamBankBin(name: 'KEB Hana Bank HCM', code: 'KEBHANAHCM', bin: '970466'),
  VietnamBankBin(name: 'Citibank', code: 'CITIBANK', bin: '533948'),
  VietnamBankBin(name: 'CBBank', code: 'CBB', bin: '970444'),
  VietnamBankBin(name: 'CIMB', code: 'CIMB', bin: '422589'),
  VietnamBankBin(name: 'DBS Bank', code: 'DBS', bin: '796500'),
  VietnamBankBin(name: 'Vikki Bank', code: 'VIKKI', bin: '970406'),
  VietnamBankBin(name: 'VBSP', code: 'VBSP', bin: '999888'),
  VietnamBankBin(name: 'GPBank', code: 'GPB', bin: '970408'),
  VietnamBankBin(name: 'Kookmin Bank HCM', code: 'KBHCM', bin: '970463'),
  VietnamBankBin(name: 'Kookmin Bank Hà Nội', code: 'KBHN', bin: '970462'),
  VietnamBankBin(name: 'Woori Bank', code: 'WVN', bin: '970457'),
  VietnamBankBin(name: 'VRB', code: 'VRB', bin: '970421'),
  VietnamBankBin(name: 'HSBC', code: 'HSBC', bin: '458761'),
  VietnamBankBin(name: 'IBK Hà Nội', code: 'IBK-HN', bin: '970455'),
  VietnamBankBin(name: 'IBK HCM', code: 'IBK-HCM', bin: '970456'),
  VietnamBankBin(name: 'Indovina Bank', code: 'IVB', bin: '970434'),
  VietnamBankBin(name: 'United Overseas Bank', code: 'UOB', bin: '970458'),
  VietnamBankBin(name: 'Nonghyup Bank Hà Nội', code: 'NHB-HN', bin: '801011'),
  VietnamBankBin(name: 'Standard Chartered', code: 'SCVN', bin: '970410'),
  VietnamBankBin(name: 'Public Bank Vietnam', code: 'PBVN', bin: '970439'),
];
